# Generated by Django 5.0.2 on 2026-08-28 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.SmallIntegerField(default=0)),
                ('cor', models.CharField(default='#64748b', max_length=7)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Entrada — Receita'), ('DESPESA', 'Saída — Despesa')], max_length=8)),
                ('consolida_mercado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='catalogo.classificacao')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=160)),
                ('cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve ter 14 dígitos')])),
                ('categoria_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogo.categoria')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='classificacao',
            constraint=models.UniqueConstraint(fields=('workspace', 'nome'), name='uq_classificacao_nome'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('workspace', 'nome', 'tipo'), name='uq_categoria_nome_tipo'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('consolida_mercado', True)), fields=('workspace',), name='uq_categoria_mercado_por_workspace'),
        ),
        migrations.AddIndex(
            model_name='estabelecimento',
            index=models.Index(fields=['workspace', 'cnpj'], name='catalogo_es_workspa_63c556_idx'),
        ),
    ]
