# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApelidoEstabelecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(db_index=True, max_length=120)),
                ('origem', models.CharField(choices=[('MANUAL', 'Cadastrado pelo usuário'), ('CONCILIACAO', 'Aprendido ao conciliar'), ('SUGERIDO', 'Sugerido pelo sistema')], default='MANUAL', max_length=12)),
            ],
            options={
                'ordering': ['texto'],
            },
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='apelido',
            field=models.CharField(blank=True, help_text='Como você chama este lugar.', max_length=80),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cnpj_raiz',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='municipio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddConstraint(
            model_name='estabelecimento',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__gt', '')), fields=('workspace', 'cnpj'), name='uq_estabelecimento_cnpj'),
        ),
        migrations.AddField(
            model_name='apelidoestabelecimento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apelidos', to='catalogo.estabelecimento'),
        ),
        migrations.AddConstraint(
            model_name='apelidoestabelecimento',
            constraint=models.UniqueConstraint(fields=('estabelecimento', 'texto'), name='uq_apelido_texto'),
        ),
    ]
