# Generated by Django 5.0.2 on 2026-08-29 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaConsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.DateField()),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('consumo', models.DecimalField(blank=True, decimal_places=3, help_text='kWh para energia, m³ para água e gás.', max_digits=12, null=True)),
                ('leitura_anterior', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('leitura_atual', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dias_faturados', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemContaConsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeConsumidora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servico', models.CharField(choices=[('ENERGIA', 'Energia elétrica'), ('AGUA', 'Água e esgoto'), ('GAS', 'Gás encanado')], max_length=8)),
                ('codigo_cliente', models.CharField(max_length=40)),
                ('apelido', models.CharField(blank=True, max_length=80)),
                ('concessionaria', models.CharField(blank=True, max_length=80)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('senha_pdf', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['servico', 'apelido'],
            },
        ),
    ]
