# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contas', '0001_initial'),
        ('contratos', '0001_initial'),
        ('documentos', '0001_initial'),
        ('realizados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaconsumo',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_consumo', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='contaconsumo',
            name='realizado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_consumo', to='realizados.realizado'),
        ),
        migrations.AddField(
            model_name='contaconsumo',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='itemcontaconsumo',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contas.contaconsumo'),
        ),
        migrations.AddField(
            model_name='unidadeconsumidora',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_consumidoras', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='unidadeconsumidora',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='contaconsumo',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='contas.unidadeconsumidora'),
        ),
        migrations.AddConstraint(
            model_name='unidadeconsumidora',
            constraint=models.UniqueConstraint(fields=('workspace', 'servico', 'codigo_cliente'), name='uq_unidade_consumidora'),
        ),
        migrations.AddConstraint(
            model_name='contaconsumo',
            constraint=models.UniqueConstraint(fields=('unidade', 'competencia'), name='uq_conta_unidade_competencia'),
        ),
    ]
