# Generated by Django 5.0.2 on 2026-09-20 04:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalogo", "0002_apelidoestabelecimento_estabelecimento_apelido_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaOrcamentaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "teto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas",
                        to="catalogo.categoria",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["categoria__nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="metaorcamentaria",
            constraint=models.UniqueConstraint(
                fields=("workspace", "categoria"), name="uq_meta_categoria"
            ),
        ),
    ]
