# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('fiscal', '0002_consolidado_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao_original', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('parcela_atual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parcela_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('secao', models.CharField(choices=[('CORRENTE', 'Fatura corrente'), ('FUTURA', 'Parcela de fatura futura')], default='CORRENTE', max_length=8)),
                ('metodo_conciliacao', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['data_compra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveSmallIntegerField()),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('conciliada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['competencia', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apelido', models.CharField(max_length=80)),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express'), ('HIPERCARD', 'Hipercard'), ('OUTRA', 'Outra')], default='OUTRA', max_length=12)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4)),
                ('emissor', models.CharField(blank=True, max_length=80)),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dia_fechamento', models.PositiveSmallIntegerField(default=1)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('senha_pdf', models.CharField(blank=True, help_text='Senha da fatura em PDF. Guardada em claro — não use a senha do banco.', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('cartao_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='cartoes.cartao')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['apelido'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('data_compra', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('parcelas_total', models.PositiveSmallIntegerField(default=1)),
                ('observacao', models.TextField(blank=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='cartoes.cartao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='catalogo.categoria')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='catalogo.estabelecimento')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='fiscal.notafiscal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_total_informado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga')], default='FECHADA', max_length=8)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartoes.cartao')),
            ],
            options={
                'ordering': ['-competencia'],
            },
        ),
    ]
