# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cartoes', '0001_initial'),
        ('catalogo', '0002_apelidoestabelecimento_estabelecimento_apelido_and_more'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='lancamentofatura',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_fatura', to='catalogo.categoria'),
        ),
        migrations.AddField(
            model_name='lancamentofatura',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_fatura', to='catalogo.estabelecimento'),
        ),
        migrations.AddField(
            model_name='lancamentofatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='cartoes.fatura'),
        ),
        migrations.AddField(
            model_name='parcelacompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cartoes.compra'),
        ),
        migrations.AddField(
            model_name='lancamentofatura',
            name='parcela_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamento', to='cartoes.parcelacompra'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['workspace', 'data_compra'], name='cartoes_com_workspa_4345b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.UniqueConstraint(fields=('cartao', 'competencia'), name='uq_fatura_cartao_competencia'),
        ),
        migrations.AddIndex(
            model_name='parcelacompra',
            index=models.Index(fields=['competencia'], name='cartoes_par_compete_c206b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelacompra',
            constraint=models.UniqueConstraint(fields=('compra', 'numero'), name='uq_parcela_compra'),
        ),
        migrations.AddIndex(
            model_name='lancamentofatura',
            index=models.Index(fields=['fatura', 'secao'], name='cartoes_lan_fatura__b4c07f_idx'),
        ),
    ]
