# Generated by Django 5.0.2 on 2026-08-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='senha_pdf',
        ),
    ]
