# Generated by Django 5.0.2 on 2026-09-20 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoTurnaround",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ATIVO", "Em execução"),
                            ("CONCLUIDO", "Concluído"),
                            ("PAUSADO", "Pausado"),
                        ],
                        default="RASCUNHO",
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateField()),
                (
                    "meta_saldo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Saldo alvo ao término do plano.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "meta_comprometimento_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% da renda comprometida com dívidas — meta a atingir (ex.: 30).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ClassificacaoContrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "ESSENCIAL",
                                "Essencial — mantém a vida funcionando, nunca cortar",
                            ),
                            (
                                "BOM",
                                "Bom — aumenta previsibilidade ou capacidade produtiva",
                            ),
                            (
                                "RUIM",
                                "Ruim — juros altos, consumo emocional ou sem retorno",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("justificativa", models.TextField(blank=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes_turnaround",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes",
                        to="turnaround.planoturnaround",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "contrato__descricao"],
            },
        ),
        migrations.AddConstraint(
            model_name="classificacaocontrato",
            constraint=models.UniqueConstraint(
                fields=("plano", "contrato"), name="uq_classificacao_plano_contrato"
            ),
        ),
    ]
