# Generated by Django 5.0.2 on 2026-08-28 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoMercado',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('competencia', models.DateField()),
                ('quantidade_notas', models.IntegerField()),
                ('quantidade_itens', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ticket_medio', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'vw_mercado_consolidado',
                'ordering': ['-competencia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chave_acesso', models.CharField(max_length=44, validators=[django.core.validators.RegexValidator('^\\d{44}$', 'Chave de acesso deve ter 44 dígitos')])),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('modelo', models.CharField(blank=True, max_length=2)),
                ('serie', models.CharField(blank=True, max_length=3)),
                ('numero', models.CharField(blank=True, max_length=9)),
                ('cnpj_emitente', models.CharField(blank=True, max_length=14)),
                ('nome_emitente', models.CharField(blank=True, max_length=200)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_tributos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('forma_pagamento', models.CharField(blank=True, max_length=60)),
                ('protocolo', models.CharField(blank=True, max_length=30)),
                ('qr_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando consulta na SEFAZ'), ('IMPORTADA', 'Importada'), ('ERRO', 'Erro na consulta'), ('MANUAL', 'Digitada manualmente')], default='PENDENTE', max_length=10)),
                ('erro_consulta', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='catalogo.categoria')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='catalogo.estabelecimento')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_item', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unidade', models.CharField(blank=True, max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogo.categoria')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscal')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['workspace', 'data_emissao'], name='fiscal_nota_workspa_cad7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['workspace', 'status'], name='fiscal_nota_workspa_3170b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('workspace', 'chave_acesso'), name='uq_nota_chave'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscal',
            constraint=models.UniqueConstraint(fields=('nota', 'numero_item'), name='uq_item_nota'),
        ),
    ]
