# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
        ('fiscal', '0002_consolidado_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoNota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Cartão de crédito'), ('DEBITO', 'Cartão de débito'), ('CREDITO_LOJA', 'Crédito da loja'), ('VALE_ALIMENTACAO', 'Vale alimentação'), ('VALE_REFEICAO', 'Vale refeição'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('bandeira', models.CharField(blank=True, max_length=20)),
                ('autorizacao', models.CharField(blank=True, help_text='cAut da NFC-e. Quando a fatura também traz, a conciliação vira exata.', max_length=30)),
                ('confirmado', models.BooleanField(default=False)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='cartoes.cartao')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='fiscal.notafiscal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
