# Generated by Django 5.0.2 on 2026-08-28 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Entrada — Receita'), ('DESPESA', 'Saída — Despesa')], max_length=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Sempre positivo. O sinal vem de `tipo`.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequencia', models.CharField(choices=[('M', 'Mensal'), ('B', 'Bimestral'), ('T', 'Trimestral'), ('S', 'Semestral'), ('A', 'Anual'), ('U', 'Única')], default='M', max_length=1)),
                ('reajuste_anual_pct', models.DecimalField(decimal_places=3, default=0, help_text='% aplicado a cada 12 meses na projeção (0 = sem reajuste).', max_digits=6)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_rescisao', models.DateField(blank=True, help_text='Se preenchida, corta a projeção nesta data.', null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('RESCINDIDO', 'Rescindido'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=12)),
                ('tipo_registro', models.CharField(choices=[('CONTRATO_FECHADO', 'Contrato fechado'), ('PREVISAO', 'Previsão'), ('RECORRENCIA', 'Recorrência sem contrato')], default='CONTRATO_FECHADO', max_length=20)),
                ('tipo_conta', models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=10)),
                ('forma_pagamento', models.CharField(blank=True, max_length=60)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('MERCADO', 'Consolidado do mercado (NFC-e)'), ('IMPORTACAO', 'Importação de planilha'), ('OFX', 'Extrato bancário')], default='MANUAL', max_length=12)),
                ('observacao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='catalogo.categoria')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='catalogo.classificacao')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='catalogo.estabelecimento')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['tipo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaPrevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indice', models.PositiveSmallIntegerField()),
                ('competencia', models.DateField()),
                ('data_planejada', models.DateField()),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade_planejada', models.PositiveSmallIntegerField()),
                ('espacamento_dias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='contratos.contrato')),
            ],
            options={
                'ordering': ['data_planejada'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['workspace', 'tipo', 'status'], name='contratos_c_workspa_b6f36c_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['workspace', 'data_inicio', 'data_fim'], name='contratos_c_workspa_7c1a2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(check=models.Q(('data_fim__gte', models.F('data_inicio'))), name='ck_contrato_periodo_valido'),
        ),
        migrations.AddIndex(
            model_name='parcelaprevista',
            index=models.Index(fields=['competencia'], name='contratos_p_compete_73abe1_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelaprevista',
            constraint=models.UniqueConstraint(fields=('contrato', 'indice'), name='uq_parcela_contrato_indice'),
        ),
    ]
