# Generated by Django 5.0.2 on 2026-08-28 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Entrada — Receita'), ('DESPESA', 'Saída — Despesa')], max_length=8)),
                ('competencia', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('forma_pagamento', models.CharField(blank=True, max_length=60)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('MERCADO', 'Consolidado do mercado (NFC-e)'), ('IMPORTACAO', 'Importação de planilha'), ('OFX', 'Extrato bancário')], default='MANUAL', max_length=12)),
                ('competencia_mercado', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizados', to='catalogo.categoria')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizados', to='contratos.contrato')),
                ('parcela', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizado', to='contratos.parcelaprevista')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-data_pagamento'],
                'indexes': [models.Index(fields=['workspace', 'competencia'], name='realizados__workspa_bf36bd_idx'), models.Index(fields=['workspace', 'tipo', 'competencia'], name='realizados__workspa_5f246f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='realizado',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'MERCADO')), fields=('workspace', 'competencia_mercado'), name='uq_realizado_mercado_mes'),
        ),
    ]
