# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documentos', '0001_initial'),
        ('realizados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Holerite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.CharField(blank=True, max_length=160)),
                ('competencia', models.DateField()),
                ('tipo_folha', models.CharField(choices=[('MENSAL', 'Folha mensal'), ('DECIMO_TERCEIRO_ADIANTAMENTO', '13º — adiantamento'), ('DECIMO_TERCEIRO_INTEGRAL', '13º — integral'), ('FERIAS', 'Férias'), ('RESCISAO', 'Rescisão')], default='MENSAL', max_length=32)),
                ('total_vencimentos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_inss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_fgts', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fgts_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('conferencia_ok', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holerites', to='documentos.documento')),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holerites', to='folha.empregador')),
                ('realizado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holerite', to='realizados.realizado')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='Verba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('descricao', models.CharField(max_length=120)),
                ('referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Dias, percentual ou quantidade — depende da verba.', max_digits=12, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('natureza', models.CharField(choices=[('VENCIMENTO', 'Vencimento'), ('DESCONTO', 'Desconto')], max_length=10)),
                ('holerite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbas', to='folha.holerite')),
            ],
            options={
                'ordering': ['natureza', 'codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='empregador',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__gt', '')), fields=('workspace', 'cnpj'), name='uq_empregador_cnpj'),
        ),
        migrations.AddIndex(
            model_name='holerite',
            index=models.Index(fields=['workspace', 'competencia'], name='folha_holer_workspa_354d98_idx'),
        ),
        migrations.AddConstraint(
            model_name='holerite',
            constraint=models.UniqueConstraint(fields=('workspace', 'empregador', 'competencia', 'tipo_folha'), name='uq_holerite_competencia'),
        ),
    ]
