# Generated by Django 5.0.2 on 2026-09-20 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("fiscal", "0003_pagamentonota"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaracaoIR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ano", models.PositiveSmallIntegerField()),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CONJUNTA", "Conjunta (casal)"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("nome_titular", models.CharField(blank=True, max_length=200)),
                ("cpf_titular", models.CharField(blank=True, max_length=14)),
                ("nome_conjuge", models.CharField(blank=True, max_length=200)),
                ("cpf_conjuge", models.CharField(blank=True, max_length=14)),
                ("observacao", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-ano", "modalidade"],
            },
        ),
        migrations.CreateModel(
            name="Dependente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("CONJUGE", "Cônjuge / Companheiro(a)"),
                            ("FILHO", "Filho(a)"),
                            ("ENTEADO", "Enteado(a)"),
                            ("PAI_MAE", "Pai / Mãe"),
                            ("AVO", "Avô / Avó"),
                            ("OUTRO", "Outro"),
                        ],
                        default="FILHO",
                        max_length=20,
                    ),
                ),
                (
                    "rendimento_proprio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rendimentos anuais do próprio dependente (ex: mesada, bolsa).",
                        max_digits=12,
                    ),
                ),
                (
                    "gera_deducao",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque se o dependente já declarou separadamente.",
                    ),
                ),
                (
                    "declaracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependentes",
                        to="ir.declaracaoir",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DespesaMedica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONSULTA", "Consulta médica"),
                            ("EXAME", "Exame laboratorial / imagem"),
                            ("INTERNACAO", "Internação / cirurgia"),
                            ("DENTAL", "Odontológico"),
                            ("PSICOLOGIA", "Psicologia / terapia"),
                            ("FISIOTERAPIA", "Fisioterapia"),
                            ("PLANO_SAUDE", "Plano de saúde"),
                            ("OUTROS", "Outros"),
                        ],
                        default="CONSULTA",
                        max_length=20,
                    ),
                ),
                ("prestador", models.CharField(max_length=200)),
                ("cnpj_prestador", models.CharField(blank=True, max_length=18)),
                (
                    "beneficiario",
                    models.CharField(
                        blank=True,
                        help_text="Deixe em branco para o titular. Preencha com o nome do dependente.",
                        max_length=200,
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observacao", models.CharField(blank=True, max_length=300)),
                (
                    "declaracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas_medicas",
                        to="ir.declaracaoir",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas_ir",
                        to="fiscal.notafiscal",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="OutraDedução",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EDUCACAO", "Educação"),
                            ("PREVIDENCIA_PRIVADA", "Previdência privada (PGBL)"),
                            ("PENSAO_ALIMENTICIA", "Pensão alimentícia judicial"),
                            ("LIVRO_CAIXA", "Livro-caixa (autônomo)"),
                            ("DOACAO", "Doação a fundo aprovado"),
                            ("OUTRO", "Outro"),
                        ],
                        default="EDUCACAO",
                        max_length=25,
                    ),
                ),
                (
                    "beneficiario",
                    models.CharField(
                        help_text="Titular ou nome do dependente a quem se refere.",
                        max_length=200,
                    ),
                ),
                ("instituicao", models.CharField(blank=True, max_length=200)),
                ("cnpj_instituicao", models.CharField(blank=True, max_length=18)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observacao", models.CharField(blank=True, max_length=300)),
                (
                    "declaracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outras_deducoes",
                        to="ir.declaracaoir",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "beneficiario"],
            },
        ),
        migrations.CreateModel(
            name="RendimentoCapitalVariavel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DIVIDENDO", "Dividendo (isento)"),
                            ("JCP", "JCP — Juros sobre capital próprio"),
                            ("GANHO_CAPITAL", "Ganho de capital (venda de ações)"),
                            ("FII", "FII — Fundo imobiliário"),
                            ("CRIPTOATIVO", "Criptoativo"),
                            ("RENDA_FIXA", "Renda fixa (CDB, LCI, LCA, Tesouro)"),
                            ("OUTRO", "Outro rendimento de capital"),
                        ],
                        default="DIVIDENDO",
                        max_length=20,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Nome da empresa, fundo ou ativo.", max_length=200
                    ),
                ),
                ("cnpj_emissor", models.CharField(blank=True, max_length=18)),
                ("valor_bruto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "imposto_retido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="IRRF retido na fonte — vira crédito na declaração.",
                        max_digits=12,
                    ),
                ),
                (
                    "isento",
                    models.BooleanField(
                        default=False,
                        help_text="Marque para dividendos brasileiros e rendimentos isentos por lei.",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "declaracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_variavel",
                        to="ir.declaracaoir",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.AddConstraint(
            model_name="declaracaoir",
            constraint=models.UniqueConstraint(
                fields=("workspace", "ano", "modalidade"),
                name="uq_declaracao_ir_ano_modalidade",
            ),
        ),
    ]
