# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogo', '0002_apelidoestabelecimento_estabelecimento_apelido_and_more'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_contrato', models.CharField(max_length=40)),
                ('instituicao', models.CharField(blank=True, max_length=80)),
                ('titular', models.CharField(blank=True, max_length=160)),
                ('paga_do_proprio_bolso', models.BooleanField(default=True)),
                ('sistema_amortizacao', models.CharField(choices=[('SAC', 'SAC (parcela decrescente)'), ('PRICE', 'Price (parcela constante)'), ('SACRE', 'SACRE (misto)'), ('OUTRO', 'Outro')], default='SAC', max_length=6)),
                ('prazo_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taxa_juros_anual', models.CharField(blank=True, max_length=30)),
                ('valor_operacao', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_ultima_parcela', models.DateField(blank=True, null=True)),
                ('atualizado_pelo_documento_em', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiamentos', to='catalogo.categoria')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamentos', to='documentos.documento')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['numero_contrato'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaFinanciamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveSmallIntegerField()),
                ('competencia', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('situacao', models.CharField(choices=[('PAGA', 'Paga'), ('ABERTA', 'Aberta'), ('PROJETADA', 'Projetada'), ('VENCIDA', 'Vencida')], max_length=10)),
                ('amortizacao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seguro_mip', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seguro_dfi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxa_administracao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('encargos', models.DecimalField(decimal_places=2, default=0, help_text='Multa, mora e ajuste financeiro somados.', max_digits=14)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('financiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financiamento.financiamento')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='financiamento',
            constraint=models.UniqueConstraint(fields=('workspace', 'numero_contrato'), name='uq_financiamento_contrato'),
        ),
        migrations.AddIndex(
            model_name='parcelafinanciamento',
            index=models.Index(fields=['competencia', 'situacao'], name='financiamen_compete_3a7a1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelafinanciamento',
            constraint=models.UniqueConstraint(fields=('financiamento', 'numero'), name='uq_parcela_financiamento'),
        ),
    ]
