# Generated by Django 5.0.2 on 2026-08-28 21:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('user', 'Pessoa'), ('assistant', 'Assistente')], max_length=10)),
                ('texto', models.TextField()),
                ('ferramentas_usadas', models.JSONField(blank=True, default=list)),
                ('blocos', models.JSONField(blank=True, default=list)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='assistente.conversa')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['workspace', '-atualizado_em'], name='assistente__workspa_ac92ee_idx'),
        ),
    ]
