# Generated by Django 5.0.2 on 2026-08-29 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo_hash', models.CharField(max_length=64)),
                ('tipo', models.CharField(choices=[('FATURA_CARTAO', 'Fatura de cartão de crédito'), ('CONTA_CONSUMO', 'Conta de consumo (luz, água, gás)'), ('FINANCIAMENTO', 'Demonstrativo de financiamento'), ('HOLERITE', 'Holerite'), ('DESCONHECIDO', 'Não reconhecido')], default='DESCONHECIDO', max_length=20)),
                ('status', models.CharField(choices=[('EXTRAIDO', 'Extraído, aguardando processamento'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro na extração'), ('IGNORADO', 'Ignorado pelo usuário')], default='EXTRAIDO', max_length=12)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('emitente', models.CharField(blank=True, max_length=200)),
                ('titular', models.CharField(blank=True, max_length=200)),
                ('extracao', models.JSONField(blank=True, default=dict)),
                ('avisos', models.JSONField(blank=True, default=list)),
                ('erro', models.TextField(blank=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-competencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LinhaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='documentos.documento')),
            ],
            options={
                'ordering': ['documento', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['workspace', 'tipo', 'competencia'], name='documentos__workspa_2fa852_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['workspace', 'status'], name='documentos__workspa_62e5e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('workspace', 'arquivo_hash'), name='uq_documento_hash'),
        ),
        migrations.AddConstraint(
            model_name='linhadocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'ordem'), name='uq_linha_ordem'),
        ),
    ]
