# Generated by Django 5.0.2 on 2026-08-28 20:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoMercado',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('competencia', models.DateField()),
                ('quantidade_notas', models.IntegerField()),
                ('quantidade_itens', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ticket_medio', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'vw_mercado_consolidado',
                'ordering': ['-competencia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.SmallIntegerField(default=0)),
                ('cor', models.CharField(default='#64748b', max_length=7)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Entrada — Receita'), ('DESPESA', 'Saída — Despesa')], max_length=8)),
                ('consolida_mercado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core.classificacao')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=160)),
                ('cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve ter 14 dígitos')])),
                ('categoria_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.categoria')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Entrada — Receita'), ('DESPESA', 'Saída — Despesa')], max_length=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Sempre positivo. O sinal vem de `tipo`.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequencia', models.CharField(choices=[('M', 'Mensal'), ('B', 'Bimestral'), ('T', 'Trimestral'), ('S', 'Semestral'), ('A', 'Anual'), ('U', 'Única')], default='M', max_length=1)),
                ('reajuste_anual_pct', models.DecimalField(decimal_places=3, default=0, help_text='% aplicado a cada 12 meses na projeção (0 = sem reajuste).', max_digits=6)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_rescisao', models.DateField(blank=True, help_text='Se preenchida, corta a projeção nesta data.', null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('RESCINDIDO', 'Rescindido'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=12)),
                ('tipo_registro', models.CharField(choices=[('CONTRATO_FECHADO', 'Contrato fechado'), ('PREVISAO', 'Previsão'), ('RECORRENCIA', 'Recorrência sem contrato')], default='CONTRATO_FECHADO', max_length=20)),
                ('tipo_conta', models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=10)),
                ('forma_pagamento', models.CharField(blank=True, max_length=60)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('MERCADO', 'Consolidado do mercado (NFC-e)'), ('IMPORTACAO', 'Importação de planilha'), ('OFX', 'Extrato bancário')], default='MANUAL', max_length=12)),
                ('observacao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.categoria')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.classificacao')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.estabelecimento')),
            ],
            options={
                'ordering': ['tipo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chave_acesso', models.CharField(max_length=44, validators=[django.core.validators.RegexValidator('^\\d{44}$', 'Chave de acesso deve ter 44 dígitos')])),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('modelo', models.CharField(blank=True, max_length=2)),
                ('serie', models.CharField(blank=True, max_length=3)),
                ('numero', models.CharField(blank=True, max_length=9)),
                ('cnpj_emitente', models.CharField(blank=True, max_length=14)),
                ('nome_emitente', models.CharField(blank=True, max_length=200)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_tributos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('forma_pagamento', models.CharField(blank=True, max_length=60)),
                ('protocolo', models.CharField(blank=True, max_length=30)),
                ('qr_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando consulta na SEFAZ'), ('IMPORTADA', 'Importada'), ('ERRO', 'Erro na consulta'), ('MANUAL', 'Digitada manualmente')], default='PENDENTE', max_length=10)),
                ('erro_consulta', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='core.categoria')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='core.estabelecimento')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_item', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unidade', models.CharField(blank=True, max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.categoria')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.notafiscal')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaPrevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indice', models.PositiveSmallIntegerField()),
                ('competencia', models.DateField()),
                ('data_planejada', models.DateField()),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade_planejada', models.PositiveSmallIntegerField()),
                ('espacamento_dias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.contrato')),
            ],
            options={
                'ordering': ['data_planejada'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('membros', models.ManyToManyField(blank=True, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Realizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Entrada — Receita'), ('DESPESA', 'Saída — Despesa')], max_length=8)),
                ('competencia', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('forma_pagamento', models.CharField(blank=True, max_length=60)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('MERCADO', 'Consolidado do mercado (NFC-e)'), ('IMPORTACAO', 'Importação de planilha'), ('OFX', 'Extrato bancário')], default='MANUAL', max_length=12)),
                ('competencia_mercado', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizados', to='core.categoria')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizados', to='core.contrato')),
                ('parcela', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizado', to='core.parcelaprevista')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscal',
            constraint=models.UniqueConstraint(fields=('nota', 'numero_item'), name='uq_item_nota'),
        ),
        migrations.AddIndex(
            model_name='parcelaprevista',
            index=models.Index(fields=['competencia'], name='core_parcel_compete_df1d76_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelaprevista',
            constraint=models.UniqueConstraint(fields=('contrato', 'indice'), name='uq_parcela_contrato_indice'),
        ),
        migrations.AddIndex(
            model_name='realizado',
            index=models.Index(fields=['workspace', 'competencia'], name='core_realiz_workspa_c940b8_idx'),
        ),
        migrations.AddIndex(
            model_name='realizado',
            index=models.Index(fields=['workspace', 'tipo', 'competencia'], name='core_realiz_workspa_e75063_idx'),
        ),
        migrations.AddConstraint(
            model_name='realizado',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'MERCADO')), fields=('workspace', 'competencia_mercado'), name='uq_realizado_mercado_mes'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['workspace', 'data_emissao'], name='core_notafi_workspa_8dc280_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['workspace', 'status'], name='core_notafi_workspa_82ca0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('workspace', 'chave_acesso'), name='uq_nota_chave'),
        ),
        migrations.AddIndex(
            model_name='estabelecimento',
            index=models.Index(fields=['workspace', 'cnpj'], name='core_estabe_workspa_8239de_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['workspace', 'tipo', 'status'], name='core_contra_workspa_4008d2_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['workspace', 'data_inicio', 'data_fim'], name='core_contra_workspa_5a5ad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(check=models.Q(('data_fim__gte', models.F('data_inicio'))), name='ck_contrato_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='classificacao',
            constraint=models.UniqueConstraint(fields=('workspace', 'nome'), name='uq_classificacao_nome'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('workspace', 'nome', 'tipo'), name='uq_categoria_nome_tipo'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('consolida_mercado', True)), fields=('workspace',), name='uq_categoria_mercado_por_workspace'),
        ),
    ]
